import type { Metadata } from "next";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import StoreProvider from "./StoreProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <StoreProvider>
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <SidebarProvider>    
                <Navbar></Navbar>
                {children}
              </SidebarProvider>
              <Footer></Footer>
            </body>
        </StoreProvider>
    </html>
  );
}
