import type { Metadata } from "next";
import { 
  ClerkProvider,
  ClerkLoading,
  ClerkLoaded  
} from "@clerk/nextjs";
import Footer from "@/components/Footer";

import StoreProvider from "./StoreProvider";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider >
        <StoreProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ClerkLoading>
              <div>Loading</div>
            </ClerkLoading>
            <ClerkLoaded>
                {children}
                <Footer></Footer>
            </ClerkLoaded>
          </body>
        </StoreProvider>
      </ClerkProvider>
    </html>
  );
}
